### ISSUE TITLE
# of glusterservers

### ISSUE THREAD

**Issue by oceanaut** [vlcty/GlusterFS-Sandbox#1]
with 'vagrant up' it is coming up with 3 glusterfs and 1 client. vagrant provisioning is 'shell' , not ansible; killed some time to figure out.why wouldnt you use shell provisioning?

**Comment by vlcty** [comment]
I don't understand your problem. Configuration of servers is done via ansible, that's right. Shell is way too complicated for that.

**Comment by oceanaut** [comment]
there is no gluster4. there is no ansible provision reference in Vagrantfile.Gluster replication is working I tested it.It is not a problem.It is a another way of doing your work.

Current machine states:

gluster1                  running (virtualbox)
gluster2                  running (virtualbox)
gluster3                  running (virtualbox)
gluster4                  running (virtualbox)
client                    running (virtualbox)

**Comment by vlcty** [comment]
I see that the README differs from the actual thing I tried out. Three gluster servers is enough. You want to have an odd number of nodes. At least for the type of setup I wanted to use.

**Comment by githubfoam** [comment]
do you use any tool for creating template files or ansible files? directory structure especially.

**Comment by vlcty** [comment]
I use Atom

**Comment by githubfoam** [comment]
I normally copy original conf file and replace parameters with vi.atom looks to save my life.

**Comment by oceanaut** [comment]
I checked on atom and see some linting tool.some atom plugin I guess.could not manage to get it running yet.I see this entries all over your files.this must be some auto stuff.how do you generate those files with atom ? 

#
# Managed by ansible
#

**Comment by vlcty** [comment]
I kind of don't understand what your problem is.

Checkout the Readme:
* Run `vagrant up` and wait until you get a bash prompt back
* Run `ansible-playbook deploy-gluster.yml`
* You now have a gluster Cluster

This required of course a working Vagrant environment (VirtualBox installed) and a working ansible installation.

Tools to use:
Vagrant -> Managed the virtual machines with VirtualBox
Ansible -> A tool to provision the virtual maschines
Atom -> Just a plain text editor for editing local files if you need to. This is optional.

Can you maybe explain a bit further what's not working and provide some console output? Oh and btw: This repo does not work under Windows.

You wrote: "do you use any tool for creating template files or ansible files? directory structure especially.". I thought you mean locally but I get the feeling you mean on the virtual machines. You don't configure manually around on the servers. That's ansibles job!

**Comment by oceanaut** [comment]
It is working.There is not a problem.My questions is about how you built this project.I create another project similar to what you do with this one.
My problem is that I create all directories and I use vim to create all files.I look into atom and I could not see how I can create directory structure,roles  and files.This is a lot of work.do you use any of this?

linter-ansible-syntax
https://atom.io/packages/linter-ansible-syntax

I thought that with atom I can create all directory structure and files.Then I can edit and customize and finally I can push  this role to "https://galaxy.ansible.com/" .

This is about speeding the process of this project.hope this clear.

**Comment by vlcty** [comment]
No, there is no tool to create an environment. At least I don't know one. But ansible roles are not that complicated. A fed directories and a few files. That's it.

**Comment by oceanaut** [comment]
I see this pattern in your template files, figure that you use some kind of tool to generate files automatically.

`#`
`# Managed by ansible `
`#`

do you use atom to check syntax of yml files ? I could not get it working. I keep using vim.I think there is no tool to check all syntax of yml files in ansible role directories parsing from top to bottom.

**Comment by vlcty** [comment]
Ahh now I get what you mean! I write that warning in any file I deploy with ansible. It's hand made. That's for users who look around directly on the server so they know that file changes will be overwritten when ansible visits next :-)

When I create a new role I take the config file from the server, adapt it to my needs and add that warning.

**Comment by oceanaut** [comment]
this pattern is only in *.j2 files.it is not in *.yml files. I customize your sandbox and develop further.it is really a lot of work.I become "copy/paste" slave.there must be some easy way to handle this situation :)

**Comment by vlcty** [comment]
I only write that in files that are copied to the server. And the comment symbol # can also be a // or a ; . That depends on the process on the remote machine.

**Comment by oceanaut** [comment]
i did not code a script to automate this.I hope I will not have to.for jinja templating.I copy existing "*.conf" and rename it as "*.conf.j2".that is the way it is right?

**Comment by oceanaut** [comment]
"hostfile" is deprecated.you need to update this repository.

**Comment by oceanaut** [comment]
warum brauchst du keepalive für gluster? funktioniert es nicht ohne keepalive?

**Comment by vlcty** [comment]
Naja das Problem ist, dass du im mount auf den Clients eine Server Adresse eintragen musst. Wenn du dann einen Node erwischt, der grade down ist, dann geht da nix. Deswegen wollte ich mit keepalived eine floating IP realisieren.

**Comment by oceanaut** [comment]
[https://www.cyberciti.biz/faq/howto-glusterfs-replicated-high-availability-storage-volume-on-ubuntu-linux/](url) es ist was du tust ? aber du hast kein HAprox laufen.[https://www.itzgeek.com/how-tos/linux/ubuntu-how-tos/install-and-configure-glusterfs-on-ubuntu-16-04-debian-8.html](url) hier kein HAproxy oder keepalive. es sieht aus wie du brauchst nicht HAproxy/keepalive.ich können testen replication zwischen gluster1 gluster2 ..

**Comment by vlcty** [comment]
So what language do you want to continue with? English or german? :-)

Why do I need HAproxy? What is the benefit?

In a normal gluster setup you don't need keepalive and a floating IP. Lets say you distribute the IP from gluster1 to your clients. The mount the filesystem and everything is okay. When gluster1 is down you can't mount it. That's why I want to use a floating IP.

**Comment by oceanaut** [comment]
:D german is a nice trip anyway. if gluster does what it is supposed to do why do u need haproxy/keepalive? those are for loadbalancing and managing session between nodes.in this case gluster nodes.do you test split-brain ? I mean your questions in the end.

**Comment by oceanaut** [comment]
"gluster1.example.lan is given in the mount point on the client. What happens when that node is not available?"  this explains below
in your configuration glusterfs is supposed to mount on storage.example.lan. if you play your deploy.yml it fails.
"mount -t glusterfs storage.example.lan:/test-volume /mnt"

the reason why you use keepalive should be serving floating IP for HA gluster nodes.If one of your glusternode is down so other nodes should pick up right away in order to prevent downtime.

**Comment by vlcty** [comment]
That's what I already said a couple of times

**Comment by oceanaut** [comment]
It does not change the fact that keepalive does not work. `ansible-playbook deploy.yml` crashes. if your configuration of keepalive works you are not supposed to mount directly on gluster node, which is not proper wie Floating IP concept.
Furthermore you can just flush jinja2 template on all servers. For gluster client this must be 
 disabled right ? `192.168.33.10   client.example.lan`


> 127.0.0.1       localhost.localdomain   localhost
::1             localhost.localdomain   localhost

{% for host in groups.gluster_cluster %}
{{ hostvars[host].ansible_ssh_host }}   {{ host }}
{% endfor %}

192.168.33.10   client.example.lan
192.168.33.10   storage.example.lan

**Comment by vlcty** [comment]
The floating IP has not nothing to do with the ansible. Ansible won't connect to the floating IP.

The vagrant box "client" mount the gluster with the floating IP. Seems like the hosts template has an error.

**Comment by oceanaut** [comment]
> The vagrant box "client" mount the gluster with "storage.example.lan". How about this? Do you understand why this does not work ? jinja2 template of keepalive is also problematic I guess. Ich versuche dir zu helfen verstehst du ? : )

**Comment by vlcty** [comment]
Submit a pull request with your changes how it should look like in your eyes. Maybe I'll understand it then.

**Comment by oceanaut** [comment]
This is my first trip on github.Am I able to pull and push with my account? Did you try running with "git clone"? Because I just do that and playbook fails.

**Comment by oceanaut** [comment]
ich habe gerade es gemacht.erste mal : )
